# Generated by Django 5.2.8 on 2025-12-02 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_post_category_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='forum/files/%Y/%m/%d/', verbose_name='첨부 파일'),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='forum/images/%Y/%m/%d/', verbose_name='이미지'),
        ),
    ]
