# Generated by Django 5.2.8 on 2025-11-30 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaboration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='color',
            field=models.CharField(choices=[('yellow', '노란색'), ('blue', '파란색'), ('green', '초록색'), ('pink', '분홍색'), ('purple', '보라색')], default='yellow', max_length=10),
        ),
    ]
