# Generated by Django migration to fix NOT NULL constraint

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaboration', '0002_post_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='position_x',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='position_y',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]

