# Generated by Django 5.2.8 on 2025-11-30 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaboration', '0003_alter_post_position_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='color',
            field=models.CharField(choices=[('yellow', '노란색'), ('blue', '파란색'), ('green', '초록색'), ('pink', '분홍색'), ('purple', '보라색'), ('orange', '주황색'), ('cyan', '청록색'), ('lime', '라임색'), ('indigo', '남색'), ('teal', '청록색')], default='yellow', max_length=10),
        ),
    ]
