# Generated by Django 5.2.8 on 2025-12-01 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaboration', '0005_add_board_post_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='attached_file',
            field=models.FileField(blank=True, null=True, upload_to='files/', verbose_name='첨부 파일'),
        ),
    ]
